#!/usr/bin/env bash
# Script that prints "To infinity and beyond" indefinitely and responds to SIGTERM by printing messages

trap 'echo "I am invincible!!!"; echo "OK"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
