#!/usr/bin/env bash
# A Bash script that loops indefinitely printing "To infinity and beyond"
# and responds to SIGTERM signal by printing "I am invincible!!!" instead of exiting

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
